### ISSUE TITLE
Name collision with mpremote run and "run script"

### ISSUE THREAD

**Issue by ricksorensen** [Josverl/mpremote_config#7]
Using mpremote 1.20.0 (from PyPi) I tried `mpremote run dumpinfo.py`, and received:
```
$ mpremote run dumpinfo.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name not defined
```
Every time I tried to `mpremote run file` I received this error. 

I then removed `~.config/mpremote` and `run` worked as expected:
```
$ mpremote run dumpinfo.py
gc_free: 18944
gc_free: 19824
stack: 476
GC: total: 22080, used: 2320, free: 19760
 No. of 1-blocks: 30, 2-blocks: 13, max blk sz: 31, max free sz: 910
--- Sys Info ---
  platform:        samd
  version:         3.4.0; MicroPython v1.20.0-111-g0000eb272 on 2023-05-23
  implementation:  (name='micropython', version=(1, 20, 0), _machine='Seeed Xiao with SAMD21G18A', _mpy=262)
.... (omitted) ...
gc_free: 19776
```
I then reinstalled the config/snippets from your repository, changed the initial commands which contained 'run script ...' to '**xrun** script ....'
```
commands = {
    "list": {
        "command": ["connect", "list"],
        "help": "List serial devices",
    },
    "xrun script='main.py'": {                 # change from run script to xrun script
        "command": ["exec", "exec( open(script).read() , globals() )"],
        "help": "Run a script on the remote device",
    },
    "md": {"command": "mkdir", "help": "alias for mkdir"},
    "del": {"command": "rm", "help": "alias for rm"},
    "dir": {"command": "ls", "help": "alias for ls"},
    "copy": {"command": "cp", "help": "alias for cp"},
}

```
Rerunning the `mpremote run dumpinfo.py` now works as expected, as did running other scripts.

This appears to because the default operation for `run` is overwritten in the mpremote function `prepare_command_expansions(config)`  which parses built-in commands first then parses commands read from `config.py`.

**Comment by Josverl** [comment]
🤐 Oops, actually I ran into this myself, and put it aside while figuring out sometime else.

I'll Rename and document the ability to override as a feature

Thanks for flagging this 👍
